### ISSUE TITLE
callback url for developer app

### ISSUE THREAD

**Issue by logicfish** [OrbitalEnterprises/orbital-esi-proxy#1]
On the readme it does not explain how to set the callback.  I had to decipher it from the redirected URL
`http://localhost:8080/evekit/api/ws/callback/eve`

**Comment by deadlybulb** [comment]
Fixed the docs, hopefully it's more clear.  Sorry about that.  Thanks for taking the time to open an issue.  I also fixed a few other things:

- If you followed the docs, you probably already figured out that `enterprises.orbital.appname` should agree with `enterprises.orbital.tomcat.path`.  I updated the docs so that is now true.  It also changes the name of the servlet to `esi-proxy` instead of `evekit`.  Of course, you can change it to whatever you like.

- I made the ESI server address configurable with `enterprises.orbital.esi.home`.  Since I released this code, they changed the server address to `esi.evetech.net`.  The old address is now a redirect, so the actual proxy will work either way, but links like `http://petstore.swagger.io/?url=http://localhost:8080/esi-proxy/latest/swagger.json` would return the unproxied service and you wouldn't be able to browse with the Swagger UI properly.

- I cleaned up the main page a bit and added substitution so the text and links point to wherever your proxy happens to be running.  In particular, the links at the bottom of the front page now take you to the Swagger UI initialized with swagger.json from your proxy (previously, it was hardcoded to esi-proxy.orbital.enterprises which is no longer running).

Thanks again!
